services:


  coppeliasim_simros2:
    build:
      context: ../..  
      dockerfile: devel/coppeliasim_simros2/Dockerfile
    environment:
      DISPLAY: $DISPLAY # x server related
    privileged: true # Needed for some gpu configurations.
    volumes:
      #- repo-data:/root/git/rap2025_wholebodycontrol/software/ROS2/ros2_ws/src/sas_coppeliasim_unitree_b1z1/
      - /tmp/.X11-unix:/tmp/.X11-unix # x server related
      - ~/.Xauthority:/root/.Xauthority # x server related
    network_mode: "host" # x server related
    ipc: "host"
    command: /bin/bash -c "
      sleep 3; 
      source /opt/ros/jazzy/setup.bash;
      export ROS_DOMAIN_ID=1;
      ~/utils/CoppeliaSim_Edu_V4_7_0_rev4_Ubuntu24_04/coppeliaSim.sh -s 0 -f app/software/ROS2/ros2_ws/src/sas_unitree_b1z1_control_template/scenes/ros2_holonomic_b1z1_setup.ttt"